### ISSUE TITLE
Names for FLAG bits

### ISSUE THREAD

**Issue by rsharris** [maragkakislab/samql#6]
From my own experience, the most difficult part of concocting a pipeline to extract something from SAM is getting the flags right. Binary flag bits packed together and represented in decimal isn't an intuitive representation. Especially when looking at an existing pipeline (or query) and trying to figure out what it intends to do.

I posed that issue to one of the SAMQL authors and he suggested I start an issue to choose names for the bits.

So the idea, as I see it, is that a SAMQL user would see each of the flags (currently there are 12) as 1 bit named entities that have value 0 or 1 (or perhaps TRUE/FALSE). So instead of "FLAG & 16 = 16" she could use something like "SEQ_IS_REV_COMP = 1" or "SEQ_IS_REV_COMP = TRUE".

Ideally the SAM spec would give names for the bits, so they would be part of that standard. But I don't see them named in the spec at https://samtools.github.io/hts-specs/SAMv1.pdf. There, a short description of each is given (second table in section 1.4).

I *do* see names for the flags, for programmer access, in
https://github.com/samtools/htslib/blob/develop/htslib/sam.h
(Interestingly, there are short descriptions there as well, and they aren't the same as those in the spec.) Would those make good names for a SAMQL user?  They are rather terse:
```
BAM_FPAIRED
BAM_FPROPER_PAIR
BAM_FUNMAP
BAM_FMUNMAP
BAM_FREVERSE
BAM_FMREVERSE
BAM_FREAD1
BAM_FREAD2
BAM_FSECONDARY
BAM_FQCFAIL
BAM_FDUP
BAM_FSUPPLEMENTARY
```
So my earlier example would become "BAM_FREVERSE = TRUE". That doesn't seem as intuitive as  it could be.

**Comment by rsharris** [comment]
I wonder if the "owners" of the SAM format would like to define flag names and add them to the SAM spec?

**Comment by mnsmar** [comment]
What about?

```
F_PAIRED
F_PROPER_PAIR
F_UNMAP
F_MATE_UNMAP
F_REVCOMP
F_MATE_REVCOMP
F_READ1
F_READ2
F_SECONDARY
F_QCFAIL
F_DUP
F_SUPP
```

The most widely used flags seem relatively short and intuitive. I would probably like `F_REVCOMP` as `F_REVERSE` or `F_REV` but the latter is closer to the spec. Having the `F_` prefix is probably useful in order to signify that we are talking about the flag field.

I find the `F_REVCOMP = TRUE` syntax more intuitive than `F_REVCOMP = 1` but will also have to look at the code again to see which one is easier/efficient to implement. Maybe this could also be possible `F_REVCOMP AND F_SUPP AND F_READ1` if we go with the former approach. However, I doubt that this one `NOT F_REVCOMP AND F_SUPP AND F_READ1` can be straightforwardly integrated so it will only work without the negation for now.

Once we have a good suggestion I will reach out the the SAM "owners" to see if they are willing to add these shortnames in the spec.

**Comment by rsharris** [comment]
That looks very reasonable to me.
